### PR TITLE
Update AutoD timing guidance

### PR DESCRIPTION
**Pull request by macmaxbh**
Based on an internal discussion amongst product group and support; update the guidance on this page to extend the validity of discovered product endpoints. Also include a validity period even if a client is running into connection-related errors so that clients do not bring down servers.

### CODE REVIEW

**Comment by macmaxbh** [comment]
@lindalu-MSFT Checking past pull requests you asked to be at-ed on pull requests to the repository? I can also provide you more context / the internal discussion thread.

**Comment by lindalu-MSFT** [comment]
@macmaxbh Are you ready to have this merged to live?

**Comment by macmaxbh** [comment]
@lindalu-MSFT Yes, please go ahead and merge to live. Thanks!

**Comment by lindalu-MSFT** [comment]
@macmaxbh Can you please remove the old MSDN links and replace with the new docs.microsoft.com link and submit another PR?  After those URL are fixed I will publish to live. Thanks, lindalu

**Pull request merged**
