### PR TITLE
Add retirement note as per PM request

### PR DESCRIPTION
**Pull request by markjjo**
These 3 operations are being retired in EXO as per https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement#getsearchablemailboxes-setholdonmailboxes-and-getholdonmailboxes-operations-in-the-ews-api

### CODE REVIEW

**Comment by markjjo** [comment]
@lindalu-MSFT Can you please merge this PR? Thanks

**Comment by lindalu-MSFT** [comment]
Hi @markjjo, there are merge conflicts that need to be resolved before I can merge to master. Can you have a look and fix and then I can merge? Thanks, lindalu

**Comment by markjjo** [comment]
@lindalu-MSFT I resolved the conflict that I think was preventing the merge to master. Can you try again? There are lot of build warnings (many due to locale in URL) in other topics, but I don't think that was preventing the merge. Thanks again.

**Comment by markjjo** [comment]
@lindalu-MSFT Thanks for merging my PR

**Pull request merged**
